// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewNode struct {
	Name string `json:"name"`
}

type Node struct {
	ID         string     `json:"id"`
	Name       string     `json:"name"`
	Operations *Operation `json:"operations"`
}

type Operation struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
